# Generated by Django 5.0.4 on 2024-05-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapesphere', '0004_remove_classschedule_class_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciBilgileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('soyisim', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=15)),
                ('kredi_karti_numarasi', models.CharField(max_length=16)),
                ('son_kullanma_tarihi', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
