# Generated by Django 5.0.4 on 2024-05-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapesphere', '0005_kullanicibilgileri_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='kullanicibilgileri',
            name='cvv',
        ),
    ]
