# Generated by Django 5.0.4 on 2024-05-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapesphere', '0006_contact_remove_kullanicibilgileri_cvv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='cvv',
        ),
        migrations.AddField(
            model_name='kullanicibilgileri',
            name='cvv',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
